services:
  db:
    # Use a lightweight PostgreSQL image
    image: postgres:17-alpine
    container_name: ytnk_db
    restart: always
    environment:
      # These variables set up the database, user, and password
      - POSTGRES_USER=ytnk_user
      - POSTGRES_PASSWORD=ytnk_password
      - POSTGRES_DB=ytnk_db
    ports:
      # Map the container's port 5432 to host's port 6059
      - "6059:5432"
    volumes:
      # Persist the database data
      - postgres_data:/var/lib/postgresql/data/

  backend:
    # Build the image from the Dockerfile in the './backend' directory
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ytnk_backend
    restart: always
    # This ensures the backend service starts only after the db service is healthy
    depends_on:
      - db
    ports:
      # Map the container's port 8000 to the host's port 8000
      - "8000:8000"
    volumes:
      # Mount the local backend directory to the container for live code reloading
      - ./backend:/usr/src/app
    env_file:
      # Load environment variables from the .env file in the backend directory
      - ./backend/.env

volumes:
  # Define the volume for persistent storage
  postgres_data:
