// frontend/src/lib/api/applicants.ts

import apiClient from './base';
import { AxiosResponse } from 'axios';

// --- Interfaces based on the backend schemas and models ---

/**
 * Interface for the full Applicant object returned from the API.
 * Corresponds to backend's schemas_applicants.Applicant / Applicant model.
 */
export interface Applicant {
    applicant_id: string; // uuid.UUID in backend, represented as string in frontend
    first_name: string;
    last_name: string;
    email: string;
    phone_number: string | null;
    linkedin_profile_url: string | null;
    github_profile_url: string | null;
    // Note: The 'applications' relationship is typically omitted in basic API responses
    // or loaded via a separate endpoint, but is kept out of this simple interface for now.
}

/**
 * Interface for creating a new Applicant.
 * Corresponds to backend's schemas_applicants.ApplicantCreate.
 * applicant_id is omitted as it's generated by the backend.
 */
export interface ApplicantCreate {
    first_name: string;
    last_name: string;
    email: string;
    phone_number?: string | null;
    linkedin_profile_url?: string | null;
    github_profile_url?: string | null;
}

/**
 * Interface for updating an existing Applicant.
 * Corresponds to backend's schemas_applicants.ApplicantUpdate.
 * All fields are optional to allow partial updates.
 */
export interface ApplicantUpdate {
    first_name?: string;
    last_name?: string;
    email?: string;
    phone_number?: string | null;
    linkedin_profile_url?: string | null;
    github_profile_url?: string | null;
}

// --- Applicant API Functions ---
const APPLICANTS_BASE_PATH = '/applicants';

/**
 * Creates a new applicant.
 * @param applicantData The data for the new applicant.
 * @returns A promise that resolves to the created Applicant object.
 * API Endpoint: POST /applicants/
 */
export const createApplicant = (
    applicantData: ApplicantCreate
): Promise<AxiosResponse<Applicant>> => {
    return apiClient.post(APPLICANTS_BASE_PATH, applicantData);
};

/**
 * Retrieves a single applicant by their ID.
 * @param applicantId The UUID (as string) of the applicant.
 * @returns A promise that resolves to the Applicant object.
 * API Endpoint: GET /applicants/{applicant_id}
 */
export const getApplicant = (
    applicantId: string
): Promise<AxiosResponse<Applicant>> => {
    return apiClient.get(`${APPLICANTS_BASE_PATH}/${applicantId}`);
};

/**
 * Retrieves a list of applicants with optional pagination.
 * @param skip The number of items to skip (default 0).
 * @param limit The maximum number of items to return (default 100).
 * @returns A promise that resolves to an array of Applicant objects.
 * API Endpoint: GET /applicants/
 */
export const getApplicants = (
    skip: number = 0,
    limit: number = 100
): Promise<AxiosResponse<Applicant[]>> => {
    return apiClient.get(APPLICANTS_BASE_PATH, {
        params: { skip, limit },
    });
};

/**
 * Updates an existing applicant's information.
 * @param applicantId The UUID (as string) of the applicant to update.
 * @param updateData The fields to update.
 * @returns A promise that resolves to the updated Applicant object.
 * API Endpoint: PUT /applicants/{applicant_id}
 */
export const updateApplicant = (
    applicantId: string,
    updateData: ApplicantUpdate
): Promise<AxiosResponse<Applicant>> => {
    return apiClient.put(`${APPLICANTS_BASE_PATH}/${applicantId}`, updateData);
};

/**
 * Deletes an applicant from the database.
 * @param applicantId The UUID (as string) of the applicant to delete.
 * @returns A promise that resolves upon successful deletion (204 No Content).
 * API Endpoint: DELETE /applicants/{applicant_id}
 */
export const deleteApplicant = (
    applicantId: string
): Promise<AxiosResponse<void>> => {
    // The backend returns 204 No Content, so the response data type is 'void'.
    return apiClient.delete(`${APPLICANTS_BASE_PATH}/${applicantId}`);
};